services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-postgres} 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=postgres"
    restart: unless-stopped

  # etl:
  #   image: python:3.11-slim
  #   container_name: extract_load
  #   working_dir: /src
  #   volumes:
  #     - etl_data:/src
  #   depends_on:
  #     - postgres
  #     - minio
  #   logging: 
  #     driver: "json-file"
  #     options:
  #         max-size: "10m"
  #         max-file: "3"
  #         labels: "service=etl"
  #   restart: on-failure

  minio:
    image: quay.io/minio/minio
    command:
      - server
      - --console-address
      - :9001
      - /data
    container_name: minio_container
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=minio"
    restart: unless-stopped

  # streamlit:
  #   image: python:3.11-slim
  #   container_name: streamlit_container
  #   working_dir: /app
  #   volumes:
  #     - streamlit_data:/app
  #   ports:
  #     - "8501:8501"
  #   logging: 
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"
  #       labels: "service=streamlit"
  #   restart: unless-stopped


volumes:
  postgres_data:
  # etl_data:
  minio_data:
  # streamlit_data: